### ISSUE TITLE
Incorrect error regarding OIDC Issuer URL value

### ISSUE THREAD

**Issue by cidrbl0ck** [gregtwallace/legocerthub-frontend#7]
(Not sure if this is the correct repo to file this issue under)

Relevant piece of current config file:

```
'config_version': 3
'bind_address': '10.2.3.4'
'https_port': 443
'http_port': 80
# enable_http_redirect': true
'log_level': 'debug'
'serve_frontend': true
'cors_permitted_crossorigins': null
'certificate_name': 'QuickSSL_Dev'
auth:
    oidc:
        # the first three fields are specified by your OIDC provider:
        # issuer URL might be very picky (e.g., requiring the trailing forward slash)
        issuer_url: 'https://company.okta.com/'
        client_id: 'id'
        client_secret: 'secret'
        # the redirect url must be the fqdn of your BACKEND certwarden server, and
        # the exact path specified here:
        api_redirect_uri: 'https://quickssl-dev.company.net/certwarden/api/v1/app/auth/oidc/callback'
    local:
        enabled: true
```

Notice the trailing slash on the value for issuer_url. With that slash present, restarting gives me this error:

`{"level":"error","ts":"2025-06-24T14:28:55.575Z","caller":"auth/service.go:126","msg":"auth: failed to create oidc provider (oidc: issuer did not match the issuer returned by provider, expected \"https://company.okta.com/\" got \"https://company.okta.com\"), oidc will not be enabled","stacktrace":"certwarden-backend/pkg/domain/app/auth.NewService\n\t/home/runner/work/certwarden/certwarden/pkg/domain/app/auth/service.go:126\ncertwarden-backend/pkg/domain/app.create\n\t/home/runner/work/certwarden/certwarden/pkg/domain/app/app_create.go:186\ncertwarden-backend/pkg/domain/app.run\n\t/home/runner/work/certwarden/certwarden/pkg/domain/app/run.go:62\ncertwarden-backend/pkg/domain/app.Run\n\t/home/runner/work/certwarden/certwarden/pkg/domain/app/run.go:23\nmain.main\n\t/home/runner/work/certwarden/certwarden/cmd/api-server/main.go:8\nruntime.main\n\t/opt/hostedtoolcache/go/1.24.2/x64/src/runtime/proc.go:283"},`

Removing that trailing slash, results in OIDC being enabled.
